"""
Photo Storage Backend
Writes and reads uploaded field photos through one of two backends:

- "local":    uploads live on disk under data/uploads/. Fastest for local dev and for cloud hosts
              with a persistent volume mounted at UPLOADS_DIR.

- "supabase": uploads are written to a Supabase Storage bucket. Public reads go directly to Supabase
              (the /uploads/<name> route 307-redirects), so backend bandwidth stays near zero.
              Enabled when SUPABASE_URL and SUPABASE_SERVICE_KEY are set.

Thumbnails are always cached on the backend's local disk (small, regenerable).
"""

import io
import os
import re
import threading
from typing import Optional

import requests

from app.core.config import settings

# Backend-process-wide HTTP session for Supabase Storage calls; thread-safe for GET/POST.
_session = requests.Session()
_session_lock = threading.Lock()

# Safe upload filenames generated by generate_safe_filename / generate_content_filename
_SAFE_NAME = re.compile(r"^upload_[A-Za-z0-9_]+\.(jpg|jpeg|png|webp)$", re.IGNORECASE)


def _project_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))


def uploads_dir() -> str:
    """Local directory where photos are stored (and read from in local mode)."""
    configured = settings.UPLOADS_DIR
    path = configured if configured else os.path.join(_project_root(), "data", "uploads")
    os.makedirs(path, exist_ok=True)
    return path


def thumbs_dir() -> str:
    """Local directory for cached thumbnails. Always on local disk, both modes."""
    configured = settings.THUMBS_DIR
    path = configured if configured else os.path.join(_project_root(), "data", "uploads_thumbs")
    os.makedirs(path, exist_ok=True)
    return path


def is_local() -> bool:
    return settings.PHOTO_STORAGE_BACKEND == "local"


def is_safe_name(name: str) -> bool:
    """Guards against path traversal in incoming filenames."""
    return bool(_SAFE_NAME.match(name or ""))


# -------------------------------------------------------------------------------------------------
# Supabase helpers
# -------------------------------------------------------------------------------------------------

def _supabase_object_url(name: str) -> str:
    return f"{settings.SUPABASE_URL}/storage/v1/object/{settings.SUPABASE_BUCKET}/{name}"


def _supabase_headers(content_type: Optional[str] = None) -> dict:
    headers = {
        "apikey": settings.SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {settings.SUPABASE_SERVICE_KEY}",
    }
    if content_type:
        headers["Content-Type"] = content_type
    return headers


def public_url(name: str) -> str:
    """Public, cacheable URL for a stored photo (Supabase mode only)."""
    return f"{settings.SUPABASE_URL}/storage/v1/object/public/{settings.SUPABASE_BUCKET}/{name}"


# -------------------------------------------------------------------------------------------------
# Public API used by the rest of the app
# -------------------------------------------------------------------------------------------------

def exists(name: str) -> bool:
    if not is_safe_name(name):
        return False
    if is_local():
        return os.path.exists(os.path.join(uploads_dir(), name))
    with _session_lock:
        resp = _session.head(_supabase_object_url(name), headers=_supabase_headers(), timeout=15)
    return resp.status_code == 200


def write_bytes(name: str, data: bytes, content_type: str = "image/jpeg") -> str:
    """
    Stores the photo under `name` and returns the public-facing URL path (e.g. /uploads/<name>),
    which is what observation records save and the frontend uses with APP_CONFIG.getEndpoint().
    """
    if not is_safe_name(name):
        raise ValueError(f"Unsafe photo filename: {name!r}")
    if is_local():
        path = os.path.join(uploads_dir(), name)
        if not os.path.exists(path):
            with open(path, "wb") as f:
                f.write(data)
    else:
        # upsert=true so a re-upload of the same byte-identical file (same content filename) is idempotent
        headers = _supabase_headers(content_type)
        headers["x-upsert"] = "true"
        with _session_lock:
            resp = _session.post(_supabase_object_url(name), data=data, headers=headers, timeout=60)
        if resp.status_code not in (200, 201):
            raise RuntimeError(f"Supabase Storage upload failed ({resp.status_code}): {resp.text[:200]}")
    return f"/uploads/{name}"


def read_bytes(name: str) -> Optional[bytes]:
    """Returns the raw photo bytes, or None if the photo is missing or the name is unsafe."""
    if not is_safe_name(name):
        return None
    if is_local():
        path = os.path.join(uploads_dir(), name)
        if not os.path.exists(path):
            return None
        with open(path, "rb") as f:
            return f.read()
    with _session_lock:
        resp = _session.get(_supabase_object_url(name), headers=_supabase_headers(), timeout=60)
    if resp.status_code != 200:
        return None
    return resp.content


def read_to_tempfile(name: str) -> Optional[str]:
    """
    Returns a local file path containing the photo bytes.
    In local mode this is the actual stored file. In supabase mode a temp copy is created.
    Caller is responsible for deleting temp files it created; local-mode paths must NOT be deleted.
    """
    if not is_safe_name(name):
        return None
    if is_local():
        path = os.path.join(uploads_dir(), name)
        return path if os.path.exists(path) else None
    data = read_bytes(name)
    if data is None:
        return None
    import tempfile
    fd, tmp_path = tempfile.mkstemp(suffix=os.path.splitext(name)[1] or ".jpg", prefix="dl_")
    os.close(fd)
    with open(tmp_path, "wb") as f:
        f.write(data)
    return tmp_path


def delete(name: str) -> bool:
    if not is_safe_name(name):
        return False
    if is_local():
        path = os.path.join(uploads_dir(), name)
        if not os.path.exists(path):
            return False
        try:
            os.remove(path)
            return True
        except OSError:
            return False
    with _session_lock:
        resp = _session.delete(_supabase_object_url(name), headers=_supabase_headers(), timeout=30)
    return resp.status_code in (200, 204, 404)
