#!/usr/bin/env node
/**
 * Build step for the static frontend on Render (or any static host that passes env vars at build).
 *
 * Reads API_BASE_URL from the environment and writes frontend/js/config.local.js so the browser
 * knows which backend to call. If API_BASE_URL isn't set, the dashboard falls back to same-origin
 * (useful when a single reverse proxy fronts both services).
 */
const fs = require("fs");
const path = require("path");

const apiBaseUrl = (process.env.API_BASE_URL || "").trim();
const outPath = path.join(__dirname, "..", "frontend", "js", "config.local.js");

if (!apiBaseUrl) {
    console.log("[build] API_BASE_URL not set — the frontend will use the same origin as itself.");
    // Remove any stale override from an earlier build
    try {
        fs.unlinkSync(outPath);
        console.log("[build] Removed stale " + outPath);
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }
    process.exit(0);
}

const banner = "// Generated by scripts/build_frontend_config.js — do not edit by hand.";
const body = `window.APP_CONFIG_OVERRIDE = { API_BASE_URL: ${JSON.stringify(apiBaseUrl.replace(/\/+$/, ""))} };`;
fs.writeFileSync(outPath, banner + "\n" + body + "\n", "utf8");
console.log("[build] Wrote " + outPath + " pointing at " + apiBaseUrl);
